accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

childcare/urls.py
from django.conf.urls import url
from . import views
   
app_name = "childcare"

urlpatterns = [
    url(r'^$', views.childcare, name="home")
]

connect/urls.py
from django.conf.urls import url
from . import views

app_name = "connect"
   
urlpatterns = [
    url(r'^$', views.connect, name="home")
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = "home"
   
urlpatterns = [
    url(r'^$', views.home, name="home")
]

learn/urls.py
from django.conf.urls import url
from . import views

app_name = "learn"

urlpatterns = [
    url(r'^$', views.learn, name='home')
]

maternaut/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^connect/', include('connect.urls')),
    url(r'^learn/', include('learn.urls')),
    url(r'^childcare/', include('childcare.urls')),
    url(r'about/$', views.about),
    url(r'^$', views.homepage, name="homepage")
]

urlpatterns += staticfiles_urlpatterns()

accounts/models.py
from django.contrib.auth.models import User
from django.db import models

childcare/models.py
from django.db import models

# Create your models here.

connect/models.py
from django.db import models
from django.contrib.auth.models import User


class user_info(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.IntegerField(default=None, null=True, unique=True)
    location_lat = models.DecimalField(max_digits=10, decimal_places=6, default=None, blank=True)
    location_lng = models.DecimalField(max_digits=10, decimal_places=6, default=None, blank=True)
    child_count = models.IntegerField(default=0, null=True)
    
    def __str__(self):
        return str(self.user)

home/models.py
from django.db import models

learn/models.py
from django.db import models

# Create your models here.

accounts/forms.py
# from django import forms
# from django.contrib.auth.forms import UserCreationForm
# # from django.contrib.auth.models import User
# from django.db import transaction
# from .models import User

# class SignUpForm(UserCreationForm):
#     # first_name = forms.CharField(label='First Name', required=False)
#     # last_name = forms.CharField(label='Last Name', required=False)
#     # # verify_code = forms.IntegerField(required=False)
#     # email = forms.EmailField(max_length=254, help_text='Required a valid email address.', required=False)
#     # phone_number = forms.RegexField(regex=r'^\+?1?\d{9,15}$')
#     # phone_number = forms.IntegerField(null=False, required=True)

#     class Meta(UserCreationForm.Meta):
#         model = User
#         fields = [
#                     'username',
#                     'phone',
#                     # 'verify_code',
#                     'password1',
#                     'password2',
#                 ]

#     @transaction.atomic
#     def save(self, commit=True):
#         user = super().save(commit=False)
#         user.is_executive = False
#         user.save()
#         # normal_user = NormalUser.objects.create(user=user)
#         # normal_user.first_name = self.cleaned_data['first_name']
#         # normal_user.last_name = self.cleaned_data['last_name']
#         return user

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            # log the user in
            return redirect('home:home')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home:home')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('homepage')

childcare/views.py
from django.shortcuts import render
from scrapers import baby
import json

def childcare(request):
    if request.method == 'POST':
        city = request.POST.get('city')
        babysitters = baby.get_babysitters(city)
        babysitters = json.loads(babysitters)
        print(babysitters)
    else:
         babysitters = baby.get_babysitters('delhi') 
         babysitters = json.loads(babysitters)  
    return render(request, 'childcare/childcare.html', {'babysitters':babysitters})

connect/views.py
from django.shortcuts import render

def connect(request):
    return render(request, 'connect/connect.html')

home/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home/home.html')

learn/views.py
from django.shortcuts import render
from scrapers import youtube_crawl
import json

def learn(request):
    if request.method == 'POST':
        query = request.POST.get('query')
        video_ids = youtube_crawl.youtube_crawler(query)
        video_ids = json.loads(video_ids)
        return render(request, 'learn/learn.html', {'video_ids': video_ids})
    return render(request, 'learn/learn.html')

maternaut/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request, 'homepage.html')

def about(request):
    return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block page_header %}
<h3>Login Below</h3>
{% endblock %}
{% block content %}
<script>
        window.onload = function() {
            document.getElementById('id_username').setAttribute('placeholder', 'Enter your Username');
            document.getElementById('id_password').setAttribute('placeholder', 'Password');
        }
    </script>
    <div class="row text-center">
            <div class="col align-self-center">
                <img src="{% static '/svg/login_illust.svg' %}" alt="" style="height: 280px; width: 480px;">
            </div>
            </div>
    <form action="{% url 'accounts:login' %}" class="site-form d-flex flex-column align-items-center" method="post" >
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Login">
    </form>
{% endblock %}

{% block auth_button %}
<a class="btn btn-primary ml-auto" role="button" href="{% url 'accounts:signup' %}">Sign Up</a>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block page_header %}
<h3>Create Account</h3>
{% endblock %}
{% block content %}
<script>
    window.onload = function() {
        document.getElementById('id_username').setAttribute('placeholder', 'Enter a Username');
        document.getElementById('id_password1').setAttribute('placeholder', 'Password');
        document.getElementById('id_password2').setAttribute('placeholder', 'Confirm Password');
    }
</script>
    
    <div class="row text-center">
        <div class="col align-self-center">
            <img src="{% static '/svg/signup_illust.svg' %}" alt="" style="height: 280px; width: 480px;">
        </div>
        </div>

    <form action="/accounts/signup/" method="post" class="site-form mt-5 h-100">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

{% block auth_button %}
<a class="btn btn-primary ml-auto" role="button" href="{% url 'accounts:login' %}">Sign In</a>
{% endblock %}

childcare/templates/childcare/childcare.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block page_header %}
    <h3>Babysitters</h3>
{% endblock %}
{% block content %}
<script>
    function initMap() {
        if(navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
      }
      else{
        alert("Location is not supported by your browser.");
      }
      function showPosition(position) {
        latlng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
        // marker.setPosition(latlng);
        // map.setCenter(latlng);
        // map.setZoom(16);
        let cityname;
        var geocoder = new google.maps.Geocoder();
        geocoder.geocode({'latLng': latlng}, function (results, status) {
       if(status == google.maps.GeocoderStatus.OK) {           // if geocode success
    //   document.getElementById('maps_search').value = results[0].formatted_address;
    //   lat =   results[0].geometry.location.lat().toFixed(6);
    //   lng =   results[0].geometry.location.lng().toFixed(6);
    //   full_add = results[0].formatted_address;
         var add_comp = results[0].address_components
         for(var i=0;i<add_comp.length;i++){
             if(add_comp[i].types[0] == "administrative_area_level_1"){
                $.post(
                    "{% url 'childcare:home' %}",
                    {
                        city: '"' + add_comp[i].long_name + '"'
                    },
                    function(data, status) {
                        console.log("success");
                    });
                break;
             }
         }
        console.log(cityname);
      }
    });
  }
    }

</script>
<script src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyDV--RWSFF8_6LWSGPd4fTAzI5RylVF2c0&callback=initMap"
async defer></script>
<div class="container">
    <form action="{% url 'childcare:home'%}" method="post">
        {% csrf_token %}
        <input type="text" name="city" id="childcare_text" value="delhi" placeholder="Enter City"> 
        <input type="submit" value="search" class="ml-2 mb-4">
    </form>
    <div id="babysitters" class="text-center">
    {% for babysitter in babysitters %}
    <div class="d-flex justify-content-center">
    <div class="card w-50">
        <div class="card-body">
            <h5 class="card-title">{{babysitter.name.lng_cont_name}}</h5>
            <a href="{{babysitter.link}}" class="btn btn-primary">Know More</a>
        </div>
        </div>
    </div>
    {% endfor %}
</div>
</div>
{% endblock %}

{% block auth_button %}
<form action="{% url 'accounts:logout' %}" method="post">
    {% csrf_token %}
<button class="btn btn-danger ml-auto" type="submit">Logout</button>
</form>
{% endblock %}

connect/templates/connect/connect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Maternaut | Connect</title>
</head>
<body>
    <h1>Connect with single parents in your city!</h1>
    <div></div>
</body>
</html>

home/templates/home/home.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block page_header %}
    <h3>Home</h3>
{% endblock %}

{% block content %}
<div class="container">
    <div id="home_menu" class="row justify-content-center mt-3">
        <div id="home_menu_item1" class=''>
            <div class="card" style="width: 18rem;">
                    <img src="{% static '/svg/home_babysit_illust.svg' %}" class="card-img-top" alt="" height="195" width="286">
                    <div class="card-body">
                        <h5 class="card-title">Babysitters near you</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="{% url 'childcare:home' %}" class="btn btn-primary">Find Babysitters</a>
                    </div>
                    </div>
            <!-- <a href="{% url 'childcare:home' %}" class="btn btn-primary">Find Babysitters</a> -->
        </div>
        <div id="home_menu_item2" class="h-100 ml-5">
                <div class="card" style="width: 18rem;">
                        <img src="{% static '/svg/home_learn_illust.svg' %}" class="card-img-top" alt="">
                        <div class="card-body">
                            <h5 class="card-title">Learn New Skills</h5>
                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                            <a href="{% url 'learn:home' %}" class="btn btn-primary">Learn & Earn</a>
                        </div>
                        </div>
            <!-- <a href="{% url 'learn:home' %}" class="btn btn-primary">Skills & Jobs</a> -->
        </div>
        <div id="home_menu_item3" class="h-100 ml-5">
                <div class="card" style="width: 18rem;">
                        <img src="{% static '/svg/home_connect_illust.svg' %}" class="card-img-top" alt=""  height="195" width="286">
                        <div class="card-body">
                            <h5 class="card-title">Make connections</h5>
                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                            <a href="{% url 'connect:home' %}" class="btn btn-primary">Connect</a>
                        </div>
                        </div>
            <!-- <a href="{% url 'connect:home' %}" class="btn btn-primary">Connect</a> -->
        </div>
    </div>

    <div class="row fixed-bottom">
        <div class="col d-flex flex-row-reverse">
            <img src="{% static '/svg/home_illust.svg' %}" alt="" height="180" width="320px">
        </div>
    </div>
</div>
{% endblock %}

{% block auth_button %}
<form action="{% url 'accounts:logout' %}" method="post">
    {% csrf_token %}
<button class="btn btn-danger ml-auto" type="submit">Logout</button>
</form>
{% endblock %}

learn/templates/learn/learn.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block page_header %}
    <h3>Learn</h3>
{% endblock %}

{% block content %}
    <div class="container">
        <form action="{% url 'learn:home'%}" method="post" class="align-items-center">
            {% csrf_token %}
            <input type="text" name="query">
            <input type="submit" value="search">
        </form>
        <div id="babysitters" class="text-center">
        {% for video_id in video_ids %}
        <div class="d-flex justify-content-center">
        <div class="card w-50">
            <iframe width="420" height="315"
                src="https://www.youtube.com/embed/{{video_id.id}}">
            </iframe>
        </div>
        </div>
    </div>
        {% endfor %}
    </div>
</div>
    {% endblock %}

{% block auth_button %}
<form action="{% url 'accounts:logout' %}" method="post">
    {% csrf_token %}
<button class="btn btn-danger ml-auto" type="submit">Logout</button>
</form>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>About</title>
</head>
<body>
    <h1>We are MaterNautians</h1>
</body>
</html>

templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    <script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css'%}">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    <nav class="navbar navbar-light navbar-expand bg-dark text-light navigation-clean">
        <div class="container">
            <a class="navbar-brand text-primary" href="{% url 'homepage' %}">MATERNAUT</a>
            <div id="navcol-1">
                {% block page_header %}
                {% endblock %}
            </div>
            <div id="navcol-1">
                {% block auth_button %}
                {% endblock %}
            </div>
        </div>
    </nav>
    <section class="features-icons text-center">
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>
        </section>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

templates/homepage.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Home - Maternaut</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

    <script>
        function opensignup() {
            window.open("/accounts/signup");
        }
    </script>
</head>

<body>
    <nav class="navbar navbar-light navbar-expand bg-light navigation-clean">
        <div class="container"><a class="navbar-brand" href="#">MATERNAUT</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"></button>
            <div class="collapse navbar-collapse" id="navcol-1"><a class="btn btn-primary ml-auto" role="button" href="{% url 'accounts:login' %}">Sign In</a></div>
        </div>
    </nav>
    <header class="masthead text-white text-center" style="background:url('{% static '/img/bg-masthead.jpg' %}')no-repeat center center;background-size:cover;">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-xl-9 mx-auto">
                    <h1 class="mb-5">Let Maternaut be your life partner.</h1>
                </div>
				
                <div class="col-xl-4 mx-auto">
				<form class="align-items-center">
					<button class="btn btn-primary btn-block btn-lg" onclick="opensignup()">Sign up!</button>
				</form>
				</div>
            </div>
        </div>
    </header>
    <section class="features-icons bg-light text-center">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="mx-auto features-icons-item mb-5 mb-lg-0 mb-lg-3">
                        <div class="d-flex features-icons-icon"><i class="icon-screen-desktop m-auto text-primary" data-bs-hover-animate="pulse"></i></div>
                        <h3>BABYSITTERS</h3>
                        <p class="lead mb-0">Find Babysitters near you.</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="mx-auto features-icons-item mb-5 mb-lg-0 mb-lg-3">
                        <div class="d-flex features-icons-icon"><i class="icon-layers m-auto text-primary" data-bs-hover-animate="pulse"></i></div>
                        <h3>LEARN AND EARN</h3>
                        <p class="lead mb-0">Learn new skills and get jobs.</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="mx-auto features-icons-item mb-5 mb-lg-0 mb-lg-3">
                        <div class="d-flex features-icons-icon"><i class="icon-check m-auto text-primary" data-bs-hover-animate="pulse"></i></div>
                        <h3>COMMUNITY</h3>
                        <p class="lead mb-0">Connect to community.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="showcase">
        <div class="container-fluid p-0">
			<div class="row no-gutters">
                <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image:url('{% static '/img/bg-showcase-3.jpg' %}');"><span></span></div>
                <div class="col-lg-6 my-auto order-lg-1 showcase-text">
                    <h2>Baby sitters near you.</h2>
                    <p class="lead mb-0">We let you find the best babysitters near you.</p>
                </div>
            </div>
			<div class="row no-gutters">
                <div class="col-lg-6 text-white showcase-img" style="background-image:url('{% static '/img/knitting.jpg' %}');"><span></span></div>
                <div class="col-lg-6 my-auto order-lg-1 showcase-text">
                    <h2>Start learning and earning.</h2>
                    <p class="lead mb-0">Learn your favtourite skills and kickstart your carrier.</p>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image:url('{% static '/img/socialnetworks.jpg' %}');"><span></span></div>
                <div class="col-lg-6 my-auto order-lg-1 showcase-text">
                    <h2>Connect with community.</h2>
                    <p class="lead mb-0">Connect with the community and get yourself socialized.</p>
                </div>
            </div>
        </div>
    </section>
    <section class="call-to-action text-white text-center" style="background:url('{% static '/img/bg-masthead.jpg' %}') no-repeat center center;background-size:cover;">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-xl-9 mx-auto">
                    <h2 class="mb-4">Ready to get started? Sign up now!</h2>
                </div>
                <div class="col-xl-4 mx-auto">
				<form class="align-items-center">
					<button class="btn btn-primary btn-block btn-lg" onclick="opensignup()">Sign up!</button>
				</form>
				</div>
            </div>
        </div>
    </section>
    <footer class="footer bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 my-auto h-100 text-center text-lg-left">
                    <ul class="list-inline mb-2">
                        <li class="list-inline-item"><a href="#">About</a></li>
                        <li class="list-inline-item"><span>⋅</span></li>
                        <li class="list-inline-item"><a href="#">Contact</a></li>
                        <li class="list-inline-item"><span>⋅</span></li>
                        <li class="list-inline-item"><a href="#">Terms of &nbsp;Use</a></li>
                        <li class="list-inline-item"><span>⋅</span></li>
                        <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
                    </ul>
                    <p class="text-muted small mb-4 mb-lg-0">© Brand 2019. All Rights Reserved.</p>
                </div>
                <div class="col-lg-6 my-auto h-100 text-center text-lg-right">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item"><a href="#"><i class="fa fa-facebook fa-2x fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fa fa-twitter fa-2x fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fa fa-instagram fa-2x fa-fw"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="assets/js/script.min.js"></script>
</body>

</html>